import random
from models import Card, Ask


# Part Ai part mE
class Analyzer:
    @staticmethod
    def illegalAskReason(game, ask):
        s = ask.card.set

        if ask.asker == ask.asked:
            return "You can't ask yourself"
        if ask.asker.team == ask.asked.team:
            return "You can't ask a teammate"
        if not ask.asked.hand:
            return f"{ask.asked.name.capitalize()} has no cards"
        if ask.card in ask.asker.hand:
            return f"You already have {ask.card}"
        if not any(c.set == s for c in ask.asker.hand):
            return f"You have no cards in {s}"

        return None

    # Me
    @staticmethod
    def getLegalAsks(game, player):
        if not player.hand:
            return []
        opponents = [p for p in game.players if p.team != player.team]
        possibleSets = {card.set for card in player.hand}
        candidates = {
            c
            for c in Card.getAllCards()
            if c.set in possibleSets and c not in player.hand
        }
        legalAsks = []
        for card in candidates:
            for opp in opponents:
                ask = Ask(player, opp, card)
                isIllegal = Analyzer.illegalAskReason(game, ask)
                isUseless = player.isBot and opp not in game.publicInfo[card.set][card]
                if not isIllegal and not isUseless:
                    legalAsks.append(ask)
        return legalAsks

# Overall strategy generated by me written almost entirely with AI
class BotStrategy:
    selfishProb = 0.10

    @staticmethod
    def setCompletionScore(game, bot, setName):
        total = 0
        for possible in game.publicInfo[setName].values():
            total += len(possible)
        return total

    @staticmethod
    def bestAskInSet(game, bot, asks):
        return random.choice(asks)

    @staticmethod
    def selfishAsk(game, bot, legalAsks):
        setGroups = {}
        for ask in legalAsks:
            setGroups.setdefault(ask.card.set, []).append(ask)

        def setScoreKey(s):
            return (BotStrategy.setCompletionScore(game, bot, s), random.random())

        bestSet = min(setGroups, key=setScoreKey)
        return BotStrategy.bestAskInSet(game, bot, setGroups[bestSet])

    @staticmethod
    def followTeammate(game, bot, legalAsks):
        teammates = {p for p in game.players if p.team == bot.team and p != bot}
        targetSet = None
        for ask in reversed(game.asks):
            if ask.asker in teammates:
                targetSet = ask.card.set
                break
        if targetSet is None:
            return None
        setAsks = [a for a in legalAsks if a.card.set == targetSet]
        if not setAsks:
            return None
        return BotStrategy.bestAskInSet(game, bot, setAsks)

    @staticmethod
    def continueOwnSet(game, bot, legalAsks):
        if not game.asks:
            return None
        last = game.asks[-1]
        if last.asker == bot and last.gotCard:
            setAsks = [a for a in legalAsks if a.card.set == last.card.set]
            if setAsks:
                return BotStrategy.bestAskInSet(game, bot, setAsks)
        return None

    @staticmethod
    def chooseMove(game, bot):
        legalAsks = Analyzer.getLegalAsks(game, bot)
        if not legalAsks:
            return None
        ask = BotStrategy.continueOwnSet(game, bot, legalAsks)
        if ask:
            return ask
        if random.random() > BotStrategy.selfishProb:
            ask = BotStrategy.followTeammate(game, bot, legalAsks)
            if ask:
                return ask
        return BotStrategy.selfishAsk(game, bot, legalAsks)

    @staticmethod
    def resolveOutcome(ask):
        return ask.card in ask.asked.hand

    @staticmethod
    def findDeclaration(game, bot):
        teammates = {p for p in game.players if p.team == bot.team and p != bot}
        opponents = {p for p in game.players if p.team != bot.team}
        allOpponentsOut = not any(p.hand for p in opponents)

        for setName in {c.set for c in bot.hand} - game.completedSets:
            cards = list(game.publicInfo[setName].keys())
            assignments = {}
            for card in cards:
                if card in bot.hand:
                    assignments[card] = bot
                else:
                    teamPool = (game.publicInfo[setName][card] - {bot}) & teammates
                    # Drop empty-handed players — they can't hold any cards
                    teamPool = {p for p in teamPool if p.hand}
                    if len(teamPool) == 1:
                        assignments[card] = next(iter(teamPool))
                    elif allOpponentsOut and teamPool:
                        # All cards must be on our team; best-guess assign to any active teammate
                        assignments[card] = next(iter(teamPool))
                    else:
                        break
            if len(assignments) == len(cards):
                return setName, assignments
        return None, None

    @staticmethod
    def doDeclaration(app, bot, setName, recipient=None):
        app.gameState.resolveSet(setName, bot.team, source="declare")
        bot.wantsTheTurn = False
        if recipient:
            recipient.wantsTheTurn = False
            app.gameState.playerWithTurn = recipient
            msg = f"{bot.name.capitalize()} declared {setName}, passing to {recipient.name.capitalize()}!"
        else:
            msg = f"{bot.name.capitalize()} declared {setName}!"
        app.declareMessage = (msg, True)
        app.declareMessageTimer = 180
        print(f"  [BOT] {msg}")
        app.gameState.advanceTurnIfNeeded()

    @staticmethod
    def knowsFullSetWithOpponent(game, bot):
        opponents = {p for p in game.players if p.team != bot.team}
        for setName in {c.set for c in bot.hand} - game.completedSets:
            cards = list(game.publicInfo[setName].keys())
            allKnown = True
            hasOpponentCard = False
            for card in cards:
                if card in bot.hand:
                    continue
                pool = game.publicInfo[setName][card] - {bot}
                if len(pool) != 1:
                    allKnown = False
                    break
                if next(iter(pool)) in opponents:
                    hasOpponentCard = True
            if allKnown and hasOpponentCard:
                return True
        return False

    @staticmethod
    def guessDeclaration(game, bot):
        teammates = [
            p for p in game.players if p.team == bot.team and p != bot and p.hand
        ]
        for setName in {c.set for c in bot.hand} - game.completedSets:
            cards = list(game.publicInfo[setName].keys())
            assignments = {}
            for card in cards:
                if card in bot.hand:
                    assignments[card] = bot
                elif teammates:
                    assignments[card] = random.choice(teammates)
                else:
                    break
            if len(assignments) == len(cards):
                return setName, assignments
        return None, None

    @staticmethod
    def performMove(app, bot):
        game = app.gameState
        setName, _ = BotStrategy.findDeclaration(game, bot)
        bot.wantsTheTurn = BotStrategy.knowsFullSetWithOpponent(game, bot)

        waitingTeammate = None
        for p in game.players:
            if p.team == bot.team and p != bot and p.wantsTheTurn:
                waitingTeammate = p
                break
        if waitingTeammate and setName:
            BotStrategy.doDeclaration(app, bot, setName, recipient=waitingTeammate)
            return

        ask = BotStrategy.chooseMove(game, bot)
        if ask is not None:
            ask.gotCard = BotStrategy.resolveOutcome(ask)
            game.recordMove(ask)
            print(f"  [BOT] {ask}")
            return

        if setName:
            BotStrategy.doDeclaration(app, bot, setName)
            return

        if bot.hand:
            guessName, _ = BotStrategy.guessDeclaration(game, bot)
            if guessName:
                print(f"  [BOT] {bot.name} guessing declaration for {guessName}")
                BotStrategy.doDeclaration(app, bot, guessName)
                return

        print(f"  [BOT] {bot.name} is stuck — advancing turn.")
        game.advanceTurn(bot)
